/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataDifference
 */
export interface DataDifference {
    /**
     * 
     * @type {any}
     * @memberof DataDifference
     */
    atType: any | null;
    /**
     * 
     * @type {any}
     * @memberof DataDifference
     */
    baseData: any | null;
    /**
     * 
     * @type {any}
     * @memberof DataDifference
     */
    compareData: any | null;
}

/**
 * Check if a given object implements the DataDifference interface.
 */
export function instanceOfDataDifference(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "baseData" in value;
    isInstance = isInstance && "compareData" in value;

    return isInstance;
}

export function DataDifferenceFromJSON(json: any): DataDifference {
    return DataDifferenceFromJSONTyped(json, false);
}

export function DataDifferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataDifference {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'atType': json['@type'],
        'baseData': json['baseData'],
        'compareData': json['compareData'],
    };
}

export function DataDifferenceToJSON(value?: DataDifference | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@type': value.atType,
        'baseData': value.baseData,
        'compareData': value.compareData,
    };
}

