/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Identified } from './Identified';
import {
    IdentifiedFromJSON,
    IdentifiedFromJSONTyped,
    IdentifiedToJSON,
} from './Identified';

/**
 * 
 * @export
 * @interface FeatureValue
 */
export interface FeatureValue {
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    atType: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    aliasIds: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    declaredName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    declaredShortName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    documentation: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    elementId: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof FeatureValue
     */
    featureWithValue: Identified;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    isDefault: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    isImplied: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    isImpliedIncluded: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    isInitial: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    isLibraryElement: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof FeatureValue
     */
    memberElement: Identified;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    memberElementId: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    memberName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    memberShortName: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof FeatureValue
     */
    membershipOwningNamespace: Identified;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedAnnotation: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedElement: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof FeatureValue
     */
    ownedMemberElement: Identified;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedMemberElementId: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedMemberName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedMemberShortName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedRelatedElement: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    ownedRelationship: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    owner: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    owningMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    owningNamespace: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    owningRelatedElement: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    owningRelationship: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    qualifiedName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    relatedElement: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    shortName: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    source: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    target: any | null;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    textualRepresentation: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof FeatureValue
     */
    value: Identified;
    /**
     * 
     * @type {any}
     * @memberof FeatureValue
     */
    visibility: any | null;
}

/**
 * Check if a given object implements the FeatureValue interface.
 */
export function instanceOfFeatureValue(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "aliasIds" in value;
    isInstance = isInstance && "declaredName" in value;
    isInstance = isInstance && "declaredShortName" in value;
    isInstance = isInstance && "documentation" in value;
    isInstance = isInstance && "elementId" in value;
    isInstance = isInstance && "featureWithValue" in value;
    isInstance = isInstance && "isDefault" in value;
    isInstance = isInstance && "isImplied" in value;
    isInstance = isInstance && "isImpliedIncluded" in value;
    isInstance = isInstance && "isInitial" in value;
    isInstance = isInstance && "isLibraryElement" in value;
    isInstance = isInstance && "memberElement" in value;
    isInstance = isInstance && "memberElementId" in value;
    isInstance = isInstance && "memberName" in value;
    isInstance = isInstance && "memberShortName" in value;
    isInstance = isInstance && "membershipOwningNamespace" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "ownedAnnotation" in value;
    isInstance = isInstance && "ownedElement" in value;
    isInstance = isInstance && "ownedMemberElement" in value;
    isInstance = isInstance && "ownedMemberElementId" in value;
    isInstance = isInstance && "ownedMemberName" in value;
    isInstance = isInstance && "ownedMemberShortName" in value;
    isInstance = isInstance && "ownedRelatedElement" in value;
    isInstance = isInstance && "ownedRelationship" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "owningMembership" in value;
    isInstance = isInstance && "owningNamespace" in value;
    isInstance = isInstance && "owningRelatedElement" in value;
    isInstance = isInstance && "owningRelationship" in value;
    isInstance = isInstance && "qualifiedName" in value;
    isInstance = isInstance && "relatedElement" in value;
    isInstance = isInstance && "shortName" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "target" in value;
    isInstance = isInstance && "textualRepresentation" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "visibility" in value;

    return isInstance;
}

export function FeatureValueFromJSON(json: any): FeatureValue {
    return FeatureValueFromJSONTyped(json, false);
}

export function FeatureValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['@id'],
        'atType': json['@type'],
        'aliasIds': json['aliasIds'],
        'declaredName': json['declaredName'],
        'declaredShortName': json['declaredShortName'],
        'documentation': json['documentation'],
        'elementId': json['elementId'],
        'featureWithValue': IdentifiedFromJSON(json['featureWithValue']),
        'isDefault': json['isDefault'],
        'isImplied': json['isImplied'],
        'isImpliedIncluded': json['isImpliedIncluded'],
        'isInitial': json['isInitial'],
        'isLibraryElement': json['isLibraryElement'],
        'memberElement': IdentifiedFromJSON(json['memberElement']),
        'memberElementId': json['memberElementId'],
        'memberName': json['memberName'],
        'memberShortName': json['memberShortName'],
        'membershipOwningNamespace': IdentifiedFromJSON(json['membershipOwningNamespace']),
        'name': json['name'],
        'ownedAnnotation': json['ownedAnnotation'],
        'ownedElement': json['ownedElement'],
        'ownedMemberElement': IdentifiedFromJSON(json['ownedMemberElement']),
        'ownedMemberElementId': json['ownedMemberElementId'],
        'ownedMemberName': json['ownedMemberName'],
        'ownedMemberShortName': json['ownedMemberShortName'],
        'ownedRelatedElement': json['ownedRelatedElement'],
        'ownedRelationship': json['ownedRelationship'],
        'owner': json['owner'],
        'owningMembership': json['owningMembership'],
        'owningNamespace': json['owningNamespace'],
        'owningRelatedElement': json['owningRelatedElement'],
        'owningRelationship': json['owningRelationship'],
        'qualifiedName': json['qualifiedName'],
        'relatedElement': json['relatedElement'],
        'shortName': json['shortName'],
        'source': json['source'],
        'target': json['target'],
        'textualRepresentation': json['textualRepresentation'],
        'value': IdentifiedFromJSON(json['value']),
        'visibility': json['visibility'],
    };
}

export function FeatureValueToJSON(value?: FeatureValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@id': value.id,
        '@type': value.atType,
        'aliasIds': value.aliasIds,
        'declaredName': value.declaredName,
        'declaredShortName': value.declaredShortName,
        'documentation': value.documentation,
        'elementId': value.elementId,
        'featureWithValue': IdentifiedToJSON(value.featureWithValue),
        'isDefault': value.isDefault,
        'isImplied': value.isImplied,
        'isImpliedIncluded': value.isImpliedIncluded,
        'isInitial': value.isInitial,
        'isLibraryElement': value.isLibraryElement,
        'memberElement': IdentifiedToJSON(value.memberElement),
        'memberElementId': value.memberElementId,
        'memberName': value.memberName,
        'memberShortName': value.memberShortName,
        'membershipOwningNamespace': IdentifiedToJSON(value.membershipOwningNamespace),
        'name': value.name,
        'ownedAnnotation': value.ownedAnnotation,
        'ownedElement': value.ownedElement,
        'ownedMemberElement': IdentifiedToJSON(value.ownedMemberElement),
        'ownedMemberElementId': value.ownedMemberElementId,
        'ownedMemberName': value.ownedMemberName,
        'ownedMemberShortName': value.ownedMemberShortName,
        'ownedRelatedElement': value.ownedRelatedElement,
        'ownedRelationship': value.ownedRelationship,
        'owner': value.owner,
        'owningMembership': value.owningMembership,
        'owningNamespace': value.owningNamespace,
        'owningRelatedElement': value.owningRelatedElement,
        'owningRelationship': value.owningRelationship,
        'qualifiedName': value.qualifiedName,
        'relatedElement': value.relatedElement,
        'shortName': value.shortName,
        'source': value.source,
        'target': value.target,
        'textualRepresentation': value.textualRepresentation,
        'value': IdentifiedToJSON(value.value),
        'visibility': value.visibility,
    };
}

