/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Identified } from './Identified';
import {
    IdentifiedFromJSON,
    IdentifiedFromJSONTyped,
    IdentifiedToJSON,
} from './Identified';

/**
 * 
 * @export
 * @interface IntersectingRequest
 */
export interface IntersectingRequest {
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    atType: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    aliasIds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    declaredName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    declaredShortName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    documentation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    elementId?: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof IntersectingRequest
     */
    intersectingType?: Identified;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    isImplied?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    isImpliedIncluded?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    isLibraryElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    ownedAnnotation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    ownedElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    ownedRelatedElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    ownedRelationship?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    owner?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    owningMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    owningNamespace?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    owningRelatedElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    owningRelationship?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    qualifiedName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    relatedElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    shortName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    source?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    target?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IntersectingRequest
     */
    textualRepresentation?: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof IntersectingRequest
     */
    typeIntersected?: Identified;
}

/**
 * Check if a given object implements the IntersectingRequest interface.
 */
export function instanceOfIntersectingRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function IntersectingRequestFromJSON(json: any): IntersectingRequest {
    return IntersectingRequestFromJSONTyped(json, false);
}

export function IntersectingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntersectingRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'atType': json['@type'],
        'aliasIds': !exists(json, 'aliasIds') ? undefined : json['aliasIds'],
        'declaredName': !exists(json, 'declaredName') ? undefined : json['declaredName'],
        'declaredShortName': !exists(json, 'declaredShortName') ? undefined : json['declaredShortName'],
        'documentation': !exists(json, 'documentation') ? undefined : json['documentation'],
        'elementId': !exists(json, 'elementId') ? undefined : json['elementId'],
        'intersectingType': !exists(json, 'intersectingType') ? undefined : IdentifiedFromJSON(json['intersectingType']),
        'isImplied': !exists(json, 'isImplied') ? undefined : json['isImplied'],
        'isImpliedIncluded': !exists(json, 'isImpliedIncluded') ? undefined : json['isImpliedIncluded'],
        'isLibraryElement': !exists(json, 'isLibraryElement') ? undefined : json['isLibraryElement'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'ownedAnnotation': !exists(json, 'ownedAnnotation') ? undefined : json['ownedAnnotation'],
        'ownedElement': !exists(json, 'ownedElement') ? undefined : json['ownedElement'],
        'ownedRelatedElement': !exists(json, 'ownedRelatedElement') ? undefined : json['ownedRelatedElement'],
        'ownedRelationship': !exists(json, 'ownedRelationship') ? undefined : json['ownedRelationship'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'owningMembership': !exists(json, 'owningMembership') ? undefined : json['owningMembership'],
        'owningNamespace': !exists(json, 'owningNamespace') ? undefined : json['owningNamespace'],
        'owningRelatedElement': !exists(json, 'owningRelatedElement') ? undefined : json['owningRelatedElement'],
        'owningRelationship': !exists(json, 'owningRelationship') ? undefined : json['owningRelationship'],
        'qualifiedName': !exists(json, 'qualifiedName') ? undefined : json['qualifiedName'],
        'relatedElement': !exists(json, 'relatedElement') ? undefined : json['relatedElement'],
        'shortName': !exists(json, 'shortName') ? undefined : json['shortName'],
        'source': !exists(json, 'source') ? undefined : json['source'],
        'target': !exists(json, 'target') ? undefined : json['target'],
        'textualRepresentation': !exists(json, 'textualRepresentation') ? undefined : json['textualRepresentation'],
        'typeIntersected': !exists(json, 'typeIntersected') ? undefined : IdentifiedFromJSON(json['typeIntersected']),
    };
}

export function IntersectingRequestToJSON(value?: IntersectingRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@id': value.id,
        '@type': value.atType,
        'aliasIds': value.aliasIds,
        'declaredName': value.declaredName,
        'declaredShortName': value.declaredShortName,
        'documentation': value.documentation,
        'elementId': value.elementId,
        'intersectingType': IdentifiedToJSON(value.intersectingType),
        'isImplied': value.isImplied,
        'isImpliedIncluded': value.isImpliedIncluded,
        'isLibraryElement': value.isLibraryElement,
        'name': value.name,
        'ownedAnnotation': value.ownedAnnotation,
        'ownedElement': value.ownedElement,
        'ownedRelatedElement': value.ownedRelatedElement,
        'ownedRelationship': value.ownedRelationship,
        'owner': value.owner,
        'owningMembership': value.owningMembership,
        'owningNamespace': value.owningNamespace,
        'owningRelatedElement': value.owningRelatedElement,
        'owningRelationship': value.owningRelationship,
        'qualifiedName': value.qualifiedName,
        'relatedElement': value.relatedElement,
        'shortName': value.shortName,
        'source': value.source,
        'target': value.target,
        'textualRepresentation': value.textualRepresentation,
        'typeIntersected': IdentifiedToJSON(value.typeIntersected),
    };
}

