/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Identified } from './Identified';
import {
    IdentifiedFromJSON,
    IdentifiedFromJSONTyped,
    IdentifiedToJSON,
} from './Identified';

/**
 * 
 * @export
 * @interface MultiplicityRangeRequest
 */
export interface MultiplicityRangeRequest {
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    atType: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    aliasIds?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    bound?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    chainingFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    declaredName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    declaredShortName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    differencingType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    directedFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    direction?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    documentation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    elementId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    endFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    endOwningType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    feature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    featureMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    featuringType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    importedMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    inheritedFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    inheritedMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    input?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    intersectingType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isAbstract?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isComposite?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isConjugated?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isDerived?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isEnd?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isImpliedIncluded?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isLibraryElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isOrdered?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isPortion?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isReadOnly?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isSufficient?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    isUnique?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    lowerBound?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    member?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    membership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    multiplicity?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    output?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedAnnotation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedConjugator?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedDifferencing?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedDisjoining?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedElement?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedEndFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedFeature?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedFeatureChaining?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedFeatureInverting?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedFeatureMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedImport?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedIntersecting?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedMember?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedRedefinition?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedReferenceSubsetting?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedRelationship?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedSpecialization?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedSubsetting?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedTypeFeaturing?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedTyping?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    ownedUnioning?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owner?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owningFeatureMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owningMembership?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owningNamespace?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owningRelationship?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    owningType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    qualifiedName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    shortName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    textualRepresentation?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    type?: any | null;
    /**
     * 
     * @type {any}
     * @memberof MultiplicityRangeRequest
     */
    unioningType?: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof MultiplicityRangeRequest
     */
    upperBound?: Identified;
}

/**
 * Check if a given object implements the MultiplicityRangeRequest interface.
 */
export function instanceOfMultiplicityRangeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function MultiplicityRangeRequestFromJSON(json: any): MultiplicityRangeRequest {
    return MultiplicityRangeRequestFromJSONTyped(json, false);
}

export function MultiplicityRangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplicityRangeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, '@id') ? undefined : json['@id'],
        'atType': json['@type'],
        'aliasIds': !exists(json, 'aliasIds') ? undefined : json['aliasIds'],
        'bound': !exists(json, 'bound') ? undefined : json['bound'],
        'chainingFeature': !exists(json, 'chainingFeature') ? undefined : json['chainingFeature'],
        'declaredName': !exists(json, 'declaredName') ? undefined : json['declaredName'],
        'declaredShortName': !exists(json, 'declaredShortName') ? undefined : json['declaredShortName'],
        'differencingType': !exists(json, 'differencingType') ? undefined : json['differencingType'],
        'directedFeature': !exists(json, 'directedFeature') ? undefined : json['directedFeature'],
        'direction': !exists(json, 'direction') ? undefined : json['direction'],
        'documentation': !exists(json, 'documentation') ? undefined : json['documentation'],
        'elementId': !exists(json, 'elementId') ? undefined : json['elementId'],
        'endFeature': !exists(json, 'endFeature') ? undefined : json['endFeature'],
        'endOwningType': !exists(json, 'endOwningType') ? undefined : json['endOwningType'],
        'feature': !exists(json, 'feature') ? undefined : json['feature'],
        'featureMembership': !exists(json, 'featureMembership') ? undefined : json['featureMembership'],
        'featuringType': !exists(json, 'featuringType') ? undefined : json['featuringType'],
        'importedMembership': !exists(json, 'importedMembership') ? undefined : json['importedMembership'],
        'inheritedFeature': !exists(json, 'inheritedFeature') ? undefined : json['inheritedFeature'],
        'inheritedMembership': !exists(json, 'inheritedMembership') ? undefined : json['inheritedMembership'],
        'input': !exists(json, 'input') ? undefined : json['input'],
        'intersectingType': !exists(json, 'intersectingType') ? undefined : json['intersectingType'],
        'isAbstract': !exists(json, 'isAbstract') ? undefined : json['isAbstract'],
        'isComposite': !exists(json, 'isComposite') ? undefined : json['isComposite'],
        'isConjugated': !exists(json, 'isConjugated') ? undefined : json['isConjugated'],
        'isDerived': !exists(json, 'isDerived') ? undefined : json['isDerived'],
        'isEnd': !exists(json, 'isEnd') ? undefined : json['isEnd'],
        'isImpliedIncluded': !exists(json, 'isImpliedIncluded') ? undefined : json['isImpliedIncluded'],
        'isLibraryElement': !exists(json, 'isLibraryElement') ? undefined : json['isLibraryElement'],
        'isOrdered': !exists(json, 'isOrdered') ? undefined : json['isOrdered'],
        'isPortion': !exists(json, 'isPortion') ? undefined : json['isPortion'],
        'isReadOnly': !exists(json, 'isReadOnly') ? undefined : json['isReadOnly'],
        'isSufficient': !exists(json, 'isSufficient') ? undefined : json['isSufficient'],
        'isUnique': !exists(json, 'isUnique') ? undefined : json['isUnique'],
        'lowerBound': !exists(json, 'lowerBound') ? undefined : json['lowerBound'],
        'member': !exists(json, 'member') ? undefined : json['member'],
        'membership': !exists(json, 'membership') ? undefined : json['membership'],
        'multiplicity': !exists(json, 'multiplicity') ? undefined : json['multiplicity'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'output': !exists(json, 'output') ? undefined : json['output'],
        'ownedAnnotation': !exists(json, 'ownedAnnotation') ? undefined : json['ownedAnnotation'],
        'ownedConjugator': !exists(json, 'ownedConjugator') ? undefined : json['ownedConjugator'],
        'ownedDifferencing': !exists(json, 'ownedDifferencing') ? undefined : json['ownedDifferencing'],
        'ownedDisjoining': !exists(json, 'ownedDisjoining') ? undefined : json['ownedDisjoining'],
        'ownedElement': !exists(json, 'ownedElement') ? undefined : json['ownedElement'],
        'ownedEndFeature': !exists(json, 'ownedEndFeature') ? undefined : json['ownedEndFeature'],
        'ownedFeature': !exists(json, 'ownedFeature') ? undefined : json['ownedFeature'],
        'ownedFeatureChaining': !exists(json, 'ownedFeatureChaining') ? undefined : json['ownedFeatureChaining'],
        'ownedFeatureInverting': !exists(json, 'ownedFeatureInverting') ? undefined : json['ownedFeatureInverting'],
        'ownedFeatureMembership': !exists(json, 'ownedFeatureMembership') ? undefined : json['ownedFeatureMembership'],
        'ownedImport': !exists(json, 'ownedImport') ? undefined : json['ownedImport'],
        'ownedIntersecting': !exists(json, 'ownedIntersecting') ? undefined : json['ownedIntersecting'],
        'ownedMember': !exists(json, 'ownedMember') ? undefined : json['ownedMember'],
        'ownedMembership': !exists(json, 'ownedMembership') ? undefined : json['ownedMembership'],
        'ownedRedefinition': !exists(json, 'ownedRedefinition') ? undefined : json['ownedRedefinition'],
        'ownedReferenceSubsetting': !exists(json, 'ownedReferenceSubsetting') ? undefined : json['ownedReferenceSubsetting'],
        'ownedRelationship': !exists(json, 'ownedRelationship') ? undefined : json['ownedRelationship'],
        'ownedSpecialization': !exists(json, 'ownedSpecialization') ? undefined : json['ownedSpecialization'],
        'ownedSubsetting': !exists(json, 'ownedSubsetting') ? undefined : json['ownedSubsetting'],
        'ownedTypeFeaturing': !exists(json, 'ownedTypeFeaturing') ? undefined : json['ownedTypeFeaturing'],
        'ownedTyping': !exists(json, 'ownedTyping') ? undefined : json['ownedTyping'],
        'ownedUnioning': !exists(json, 'ownedUnioning') ? undefined : json['ownedUnioning'],
        'owner': !exists(json, 'owner') ? undefined : json['owner'],
        'owningFeatureMembership': !exists(json, 'owningFeatureMembership') ? undefined : json['owningFeatureMembership'],
        'owningMembership': !exists(json, 'owningMembership') ? undefined : json['owningMembership'],
        'owningNamespace': !exists(json, 'owningNamespace') ? undefined : json['owningNamespace'],
        'owningRelationship': !exists(json, 'owningRelationship') ? undefined : json['owningRelationship'],
        'owningType': !exists(json, 'owningType') ? undefined : json['owningType'],
        'qualifiedName': !exists(json, 'qualifiedName') ? undefined : json['qualifiedName'],
        'shortName': !exists(json, 'shortName') ? undefined : json['shortName'],
        'textualRepresentation': !exists(json, 'textualRepresentation') ? undefined : json['textualRepresentation'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'unioningType': !exists(json, 'unioningType') ? undefined : json['unioningType'],
        'upperBound': !exists(json, 'upperBound') ? undefined : IdentifiedFromJSON(json['upperBound']),
    };
}

export function MultiplicityRangeRequestToJSON(value?: MultiplicityRangeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@id': value.id,
        '@type': value.atType,
        'aliasIds': value.aliasIds,
        'bound': value.bound,
        'chainingFeature': value.chainingFeature,
        'declaredName': value.declaredName,
        'declaredShortName': value.declaredShortName,
        'differencingType': value.differencingType,
        'directedFeature': value.directedFeature,
        'direction': value.direction,
        'documentation': value.documentation,
        'elementId': value.elementId,
        'endFeature': value.endFeature,
        'endOwningType': value.endOwningType,
        'feature': value.feature,
        'featureMembership': value.featureMembership,
        'featuringType': value.featuringType,
        'importedMembership': value.importedMembership,
        'inheritedFeature': value.inheritedFeature,
        'inheritedMembership': value.inheritedMembership,
        'input': value.input,
        'intersectingType': value.intersectingType,
        'isAbstract': value.isAbstract,
        'isComposite': value.isComposite,
        'isConjugated': value.isConjugated,
        'isDerived': value.isDerived,
        'isEnd': value.isEnd,
        'isImpliedIncluded': value.isImpliedIncluded,
        'isLibraryElement': value.isLibraryElement,
        'isOrdered': value.isOrdered,
        'isPortion': value.isPortion,
        'isReadOnly': value.isReadOnly,
        'isSufficient': value.isSufficient,
        'isUnique': value.isUnique,
        'lowerBound': value.lowerBound,
        'member': value.member,
        'membership': value.membership,
        'multiplicity': value.multiplicity,
        'name': value.name,
        'output': value.output,
        'ownedAnnotation': value.ownedAnnotation,
        'ownedConjugator': value.ownedConjugator,
        'ownedDifferencing': value.ownedDifferencing,
        'ownedDisjoining': value.ownedDisjoining,
        'ownedElement': value.ownedElement,
        'ownedEndFeature': value.ownedEndFeature,
        'ownedFeature': value.ownedFeature,
        'ownedFeatureChaining': value.ownedFeatureChaining,
        'ownedFeatureInverting': value.ownedFeatureInverting,
        'ownedFeatureMembership': value.ownedFeatureMembership,
        'ownedImport': value.ownedImport,
        'ownedIntersecting': value.ownedIntersecting,
        'ownedMember': value.ownedMember,
        'ownedMembership': value.ownedMembership,
        'ownedRedefinition': value.ownedRedefinition,
        'ownedReferenceSubsetting': value.ownedReferenceSubsetting,
        'ownedRelationship': value.ownedRelationship,
        'ownedSpecialization': value.ownedSpecialization,
        'ownedSubsetting': value.ownedSubsetting,
        'ownedTypeFeaturing': value.ownedTypeFeaturing,
        'ownedTyping': value.ownedTyping,
        'ownedUnioning': value.ownedUnioning,
        'owner': value.owner,
        'owningFeatureMembership': value.owningFeatureMembership,
        'owningMembership': value.owningMembership,
        'owningNamespace': value.owningNamespace,
        'owningRelationship': value.owningRelationship,
        'owningType': value.owningType,
        'qualifiedName': value.qualifiedName,
        'shortName': value.shortName,
        'textualRepresentation': value.textualRepresentation,
        'type': value.type,
        'unioningType': value.unioningType,
        'upperBound': IdentifiedToJSON(value.upperBound),
    };
}

