/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortionKindRequest
 */
export interface PortionKindRequest {
}

/**
 * Check if a given object implements the PortionKindRequest interface.
 */
export function instanceOfPortionKindRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortionKindRequestFromJSON(json: any): PortionKindRequest {
    return PortionKindRequestFromJSONTyped(json, false);
}

export function PortionKindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortionKindRequest {
    return json;
}

export function PortionKindRequestToJSON(value?: PortionKindRequest | null): any {
    return value;
}

