/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortionKind
 */
export interface PortionKind {
}

/**
 * Check if a given object implements the PortionKind interface.
 */
export function instanceOfPortionKind(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PortionKindFromJSON(json: any): PortionKind {
    return PortionKindFromJSONTyped(json, false);
}

export function PortionKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortionKind {
    return json;
}

export function PortionKindToJSON(value?: PortionKind | null): any {
    return value;
}

