/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TriggerKindRequest
 */
export interface TriggerKindRequest {
}

/**
 * Check if a given object implements the TriggerKindRequest interface.
 */
export function instanceOfTriggerKindRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TriggerKindRequestFromJSON(json: any): TriggerKindRequest {
    return TriggerKindRequestFromJSONTyped(json, false);
}

export function TriggerKindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerKindRequest {
    return json;
}

export function TriggerKindRequestToJSON(value?: TriggerKindRequest | null): any {
    return value;
}

