/* tslint:disable */
/* eslint-disable */
/**
 * Systems Modeling API and Services
 * REST/HTTP platform specific model (PSM) for the Systems Modeling API and Services
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Identified } from './Identified';
import {
    IdentifiedFromJSON,
    IdentifiedFromJSONTyped,
    IdentifiedToJSON,
} from './Identified';

/**
 * 
 * @export
 * @interface ViewpointUsage
 */
export interface ViewpointUsage {
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    id: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    atType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    actorParameter: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    aliasIds: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    assumedConstraint: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    behavior: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    chainingFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    constraintDefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    declaredName: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    declaredShortName: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    definition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    differencingType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    directedFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    directedUsage: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    direction: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    documentation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    elementId: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    endFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    endOwningType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    feature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    featureMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    featuringType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    framedConcern: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    _function: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    importedMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    individualDefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    inheritedFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    inheritedMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    input: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    intersectingType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isAbstract: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isComposite: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isConjugated: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isDerived: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isEnd: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isImpliedIncluded: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isIndividual: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isLibraryElement: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isModelLevelEvaluable: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isOrdered: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isPortion: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isReadOnly: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isReference: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isSufficient: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isUnique: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    isVariation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    member: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    membership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    multiplicity: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedAction: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedAllocation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedAnalysisCase: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedAttribute: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedCalculation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedCase: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedConcern: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedConnection: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedConstraint: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedEnumeration: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedFlow: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedInterface: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedItem: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedMetadata: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedOccurrence: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedPart: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedPort: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedReference: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedRendering: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedRequirement: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedState: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedTransition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedUsage: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedUseCase: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedVerificationCase: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedView: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    nestedViewpoint: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    occurrenceDefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    output: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedAnnotation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedConjugator: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedDifferencing: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedDisjoining: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedElement: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedEndFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedFeatureChaining: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedFeatureInverting: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedFeatureMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedImport: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedIntersecting: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedMember: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedRedefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedReferenceSubsetting: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedRelationship: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedSpecialization: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedSubsetting: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedTypeFeaturing: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedTyping: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    ownedUnioning: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owner: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningDefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningFeatureMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningNamespace: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningRelationship: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    owningUsage: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    parameter: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    portionKind: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    portioningFeature: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    predicate: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    qualifiedName: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    reqId: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    requiredConstraint: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    requirementDefinition: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof ViewpointUsage
     */
    result: Identified;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    shortName: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    stakeholderParameter: any | null;
    /**
     * 
     * @type {Identified}
     * @memberof ViewpointUsage
     */
    subjectParameter: Identified;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    text: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    textualRepresentation: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
     type: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    unioningType: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    usage: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    variant: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    variantMembership: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    viewpointDefinition: any | null;
    /**
     * 
     * @type {any}
     * @memberof ViewpointUsage
     */
    viewpointStakeholder: any | null;
}

/**
 * Check if a given object implements the ViewpointUsage interface.
 */
export function instanceOfViewpointUsage(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "actorParameter" in value;
    isInstance = isInstance && "aliasIds" in value;
    isInstance = isInstance && "assumedConstraint" in value;
    isInstance = isInstance && "behavior" in value;
    isInstance = isInstance && "chainingFeature" in value;
    isInstance = isInstance && "constraintDefinition" in value;
    isInstance = isInstance && "declaredName" in value;
    isInstance = isInstance && "declaredShortName" in value;
    isInstance = isInstance && "definition" in value;
    isInstance = isInstance && "differencingType" in value;
    isInstance = isInstance && "directedFeature" in value;
    isInstance = isInstance && "directedUsage" in value;
    isInstance = isInstance && "direction" in value;
    isInstance = isInstance && "documentation" in value;
    isInstance = isInstance && "elementId" in value;
    isInstance = isInstance && "endFeature" in value;
    isInstance = isInstance && "endOwningType" in value;
    isInstance = isInstance && "feature" in value;
    isInstance = isInstance && "featureMembership" in value;
    isInstance = isInstance && "featuringType" in value;
    isInstance = isInstance && "framedConcern" in value;
    isInstance = isInstance && "_function" in value;
    isInstance = isInstance && "importedMembership" in value;
    isInstance = isInstance && "individualDefinition" in value;
    isInstance = isInstance && "inheritedFeature" in value;
    isInstance = isInstance && "inheritedMembership" in value;
    isInstance = isInstance && "input" in value;
    isInstance = isInstance && "intersectingType" in value;
    isInstance = isInstance && "isAbstract" in value;
    isInstance = isInstance && "isComposite" in value;
    isInstance = isInstance && "isConjugated" in value;
    isInstance = isInstance && "isDerived" in value;
    isInstance = isInstance && "isEnd" in value;
    isInstance = isInstance && "isImpliedIncluded" in value;
    isInstance = isInstance && "isIndividual" in value;
    isInstance = isInstance && "isLibraryElement" in value;
    isInstance = isInstance && "isModelLevelEvaluable" in value;
    isInstance = isInstance && "isOrdered" in value;
    isInstance = isInstance && "isPortion" in value;
    isInstance = isInstance && "isReadOnly" in value;
    isInstance = isInstance && "isReference" in value;
    isInstance = isInstance && "isSufficient" in value;
    isInstance = isInstance && "isUnique" in value;
    isInstance = isInstance && "isVariation" in value;
    isInstance = isInstance && "member" in value;
    isInstance = isInstance && "membership" in value;
    isInstance = isInstance && "multiplicity" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "nestedAction" in value;
    isInstance = isInstance && "nestedAllocation" in value;
    isInstance = isInstance && "nestedAnalysisCase" in value;
    isInstance = isInstance && "nestedAttribute" in value;
    isInstance = isInstance && "nestedCalculation" in value;
    isInstance = isInstance && "nestedCase" in value;
    isInstance = isInstance && "nestedConcern" in value;
    isInstance = isInstance && "nestedConnection" in value;
    isInstance = isInstance && "nestedConstraint" in value;
    isInstance = isInstance && "nestedEnumeration" in value;
    isInstance = isInstance && "nestedFlow" in value;
    isInstance = isInstance && "nestedInterface" in value;
    isInstance = isInstance && "nestedItem" in value;
    isInstance = isInstance && "nestedMetadata" in value;
    isInstance = isInstance && "nestedOccurrence" in value;
    isInstance = isInstance && "nestedPart" in value;
    isInstance = isInstance && "nestedPort" in value;
    isInstance = isInstance && "nestedReference" in value;
    isInstance = isInstance && "nestedRendering" in value;
    isInstance = isInstance && "nestedRequirement" in value;
    isInstance = isInstance && "nestedState" in value;
    isInstance = isInstance && "nestedTransition" in value;
    isInstance = isInstance && "nestedUsage" in value;
    isInstance = isInstance && "nestedUseCase" in value;
    isInstance = isInstance && "nestedVerificationCase" in value;
    isInstance = isInstance && "nestedView" in value;
    isInstance = isInstance && "nestedViewpoint" in value;
    isInstance = isInstance && "occurrenceDefinition" in value;
    isInstance = isInstance && "output" in value;
    isInstance = isInstance && "ownedAnnotation" in value;
    isInstance = isInstance && "ownedConjugator" in value;
    isInstance = isInstance && "ownedDifferencing" in value;
    isInstance = isInstance && "ownedDisjoining" in value;
    isInstance = isInstance && "ownedElement" in value;
    isInstance = isInstance && "ownedEndFeature" in value;
    isInstance = isInstance && "ownedFeature" in value;
    isInstance = isInstance && "ownedFeatureChaining" in value;
    isInstance = isInstance && "ownedFeatureInverting" in value;
    isInstance = isInstance && "ownedFeatureMembership" in value;
    isInstance = isInstance && "ownedImport" in value;
    isInstance = isInstance && "ownedIntersecting" in value;
    isInstance = isInstance && "ownedMember" in value;
    isInstance = isInstance && "ownedMembership" in value;
    isInstance = isInstance && "ownedRedefinition" in value;
    isInstance = isInstance && "ownedReferenceSubsetting" in value;
    isInstance = isInstance && "ownedRelationship" in value;
    isInstance = isInstance && "ownedSpecialization" in value;
    isInstance = isInstance && "ownedSubsetting" in value;
    isInstance = isInstance && "ownedTypeFeaturing" in value;
    isInstance = isInstance && "ownedTyping" in value;
    isInstance = isInstance && "ownedUnioning" in value;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "owningDefinition" in value;
    isInstance = isInstance && "owningFeatureMembership" in value;
    isInstance = isInstance && "owningMembership" in value;
    isInstance = isInstance && "owningNamespace" in value;
    isInstance = isInstance && "owningRelationship" in value;
    isInstance = isInstance && "owningType" in value;
    isInstance = isInstance && "owningUsage" in value;
    isInstance = isInstance && "parameter" in value;
    isInstance = isInstance && "portionKind" in value;
    isInstance = isInstance && "portioningFeature" in value;
    isInstance = isInstance && "predicate" in value;
    isInstance = isInstance && "qualifiedName" in value;
    isInstance = isInstance && "reqId" in value;
    isInstance = isInstance && "requiredConstraint" in value;
    isInstance = isInstance && "requirementDefinition" in value;
    isInstance = isInstance && "result" in value;
    isInstance = isInstance && "shortName" in value;
    isInstance = isInstance && "stakeholderParameter" in value;
    isInstance = isInstance && "subjectParameter" in value;
    isInstance = isInstance && "text" in value;
    isInstance = isInstance && "textualRepresentation" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "unioningType" in value;
    isInstance = isInstance && "usage" in value;
    isInstance = isInstance && "variant" in value;
    isInstance = isInstance && "variantMembership" in value;
    isInstance = isInstance && "viewpointDefinition" in value;
    isInstance = isInstance && "viewpointStakeholder" in value;

    return isInstance;
}

export function ViewpointUsageFromJSON(json: any): ViewpointUsage {
    return ViewpointUsageFromJSONTyped(json, false);
}

export function ViewpointUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewpointUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['@id'],
        'atType': json['@type'],
        'actorParameter': json['actorParameter'],
        'aliasIds': json['aliasIds'],
        'assumedConstraint': json['assumedConstraint'],
        'behavior': json['behavior'],
        'chainingFeature': json['chainingFeature'],
        'constraintDefinition': json['constraintDefinition'],
        'declaredName': json['declaredName'],
        'declaredShortName': json['declaredShortName'],
        'definition': json['definition'],
        'differencingType': json['differencingType'],
        'directedFeature': json['directedFeature'],
        'directedUsage': json['directedUsage'],
        'direction': json['direction'],
        'documentation': json['documentation'],
        'elementId': json['elementId'],
        'endFeature': json['endFeature'],
        'endOwningType': json['endOwningType'],
        'feature': json['feature'],
        'featureMembership': json['featureMembership'],
        'featuringType': json['featuringType'],
        'framedConcern': json['framedConcern'],
        '_function': json['function'],
        'importedMembership': json['importedMembership'],
        'individualDefinition': json['individualDefinition'],
        'inheritedFeature': json['inheritedFeature'],
        'inheritedMembership': json['inheritedMembership'],
        'input': json['input'],
        'intersectingType': json['intersectingType'],
        'isAbstract': json['isAbstract'],
        'isComposite': json['isComposite'],
        'isConjugated': json['isConjugated'],
        'isDerived': json['isDerived'],
        'isEnd': json['isEnd'],
        'isImpliedIncluded': json['isImpliedIncluded'],
        'isIndividual': json['isIndividual'],
        'isLibraryElement': json['isLibraryElement'],
        'isModelLevelEvaluable': json['isModelLevelEvaluable'],
        'isOrdered': json['isOrdered'],
        'isPortion': json['isPortion'],
        'isReadOnly': json['isReadOnly'],
        'isReference': json['isReference'],
        'isSufficient': json['isSufficient'],
        'isUnique': json['isUnique'],
        'isVariation': json['isVariation'],
        'member': json['member'],
        'membership': json['membership'],
        'multiplicity': json['multiplicity'],
        'name': json['name'],
        'nestedAction': json['nestedAction'],
        'nestedAllocation': json['nestedAllocation'],
        'nestedAnalysisCase': json['nestedAnalysisCase'],
        'nestedAttribute': json['nestedAttribute'],
        'nestedCalculation': json['nestedCalculation'],
        'nestedCase': json['nestedCase'],
        'nestedConcern': json['nestedConcern'],
        'nestedConnection': json['nestedConnection'],
        'nestedConstraint': json['nestedConstraint'],
        'nestedEnumeration': json['nestedEnumeration'],
        'nestedFlow': json['nestedFlow'],
        'nestedInterface': json['nestedInterface'],
        'nestedItem': json['nestedItem'],
        'nestedMetadata': json['nestedMetadata'],
        'nestedOccurrence': json['nestedOccurrence'],
        'nestedPart': json['nestedPart'],
        'nestedPort': json['nestedPort'],
        'nestedReference': json['nestedReference'],
        'nestedRendering': json['nestedRendering'],
        'nestedRequirement': json['nestedRequirement'],
        'nestedState': json['nestedState'],
        'nestedTransition': json['nestedTransition'],
        'nestedUsage': json['nestedUsage'],
        'nestedUseCase': json['nestedUseCase'],
        'nestedVerificationCase': json['nestedVerificationCase'],
        'nestedView': json['nestedView'],
        'nestedViewpoint': json['nestedViewpoint'],
        'occurrenceDefinition': json['occurrenceDefinition'],
        'output': json['output'],
        'ownedAnnotation': json['ownedAnnotation'],
        'ownedConjugator': json['ownedConjugator'],
        'ownedDifferencing': json['ownedDifferencing'],
        'ownedDisjoining': json['ownedDisjoining'],
        'ownedElement': json['ownedElement'],
        'ownedEndFeature': json['ownedEndFeature'],
        'ownedFeature': json['ownedFeature'],
        'ownedFeatureChaining': json['ownedFeatureChaining'],
        'ownedFeatureInverting': json['ownedFeatureInverting'],
        'ownedFeatureMembership': json['ownedFeatureMembership'],
        'ownedImport': json['ownedImport'],
        'ownedIntersecting': json['ownedIntersecting'],
        'ownedMember': json['ownedMember'],
        'ownedMembership': json['ownedMembership'],
        'ownedRedefinition': json['ownedRedefinition'],
        'ownedReferenceSubsetting': json['ownedReferenceSubsetting'],
        'ownedRelationship': json['ownedRelationship'],
        'ownedSpecialization': json['ownedSpecialization'],
        'ownedSubsetting': json['ownedSubsetting'],
        'ownedTypeFeaturing': json['ownedTypeFeaturing'],
        'ownedTyping': json['ownedTyping'],
        'ownedUnioning': json['ownedUnioning'],
        'owner': json['owner'],
        'owningDefinition': json['owningDefinition'],
        'owningFeatureMembership': json['owningFeatureMembership'],
        'owningMembership': json['owningMembership'],
        'owningNamespace': json['owningNamespace'],
        'owningRelationship': json['owningRelationship'],
        'owningType': json['owningType'],
        'owningUsage': json['owningUsage'],
        'parameter': json['parameter'],
        'portionKind': json['portionKind'],
        'portioningFeature': json['portioningFeature'],
        'predicate': json['predicate'],
        'qualifiedName': json['qualifiedName'],
        'reqId': json['reqId'],
        'requiredConstraint': json['requiredConstraint'],
        'requirementDefinition': json['requirementDefinition'],
        'result': IdentifiedFromJSON(json['result']),
        'shortName': json['shortName'],
        'stakeholderParameter': json['stakeholderParameter'],
        'subjectParameter': IdentifiedFromJSON(json['subjectParameter']),
        'text': json['text'],
        'textualRepresentation': json['textualRepresentation'],
        'type': json['type'],
        'unioningType': json['unioningType'],
        'usage': json['usage'],
        'variant': json['variant'],
        'variantMembership': json['variantMembership'],
        'viewpointDefinition': json['viewpointDefinition'],
        'viewpointStakeholder': json['viewpointStakeholder'],
    };
}

export function ViewpointUsageToJSON(value?: ViewpointUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '@id': value.id,
        '@type': value.atType,
        'actorParameter': value.actorParameter,
        'aliasIds': value.aliasIds,
        'assumedConstraint': value.assumedConstraint,
        'behavior': value.behavior,
        'chainingFeature': value.chainingFeature,
        'constraintDefinition': value.constraintDefinition,
        'declaredName': value.declaredName,
        'declaredShortName': value.declaredShortName,
        'definition': value.definition,
        'differencingType': value.differencingType,
        'directedFeature': value.directedFeature,
        'directedUsage': value.directedUsage,
        'direction': value.direction,
        'documentation': value.documentation,
        'elementId': value.elementId,
        'endFeature': value.endFeature,
        'endOwningType': value.endOwningType,
        'feature': value.feature,
        'featureMembership': value.featureMembership,
        'featuringType': value.featuringType,
        'framedConcern': value.framedConcern,
        'function': value._function,
        'importedMembership': value.importedMembership,
        'individualDefinition': value.individualDefinition,
        'inheritedFeature': value.inheritedFeature,
        'inheritedMembership': value.inheritedMembership,
        'input': value.input,
        'intersectingType': value.intersectingType,
        'isAbstract': value.isAbstract,
        'isComposite': value.isComposite,
        'isConjugated': value.isConjugated,
        'isDerived': value.isDerived,
        'isEnd': value.isEnd,
        'isImpliedIncluded': value.isImpliedIncluded,
        'isIndividual': value.isIndividual,
        'isLibraryElement': value.isLibraryElement,
        'isModelLevelEvaluable': value.isModelLevelEvaluable,
        'isOrdered': value.isOrdered,
        'isPortion': value.isPortion,
        'isReadOnly': value.isReadOnly,
        'isReference': value.isReference,
        'isSufficient': value.isSufficient,
        'isUnique': value.isUnique,
        'isVariation': value.isVariation,
        'member': value.member,
        'membership': value.membership,
        'multiplicity': value.multiplicity,
        'name': value.name,
        'nestedAction': value.nestedAction,
        'nestedAllocation': value.nestedAllocation,
        'nestedAnalysisCase': value.nestedAnalysisCase,
        'nestedAttribute': value.nestedAttribute,
        'nestedCalculation': value.nestedCalculation,
        'nestedCase': value.nestedCase,
        'nestedConcern': value.nestedConcern,
        'nestedConnection': value.nestedConnection,
        'nestedConstraint': value.nestedConstraint,
        'nestedEnumeration': value.nestedEnumeration,
        'nestedFlow': value.nestedFlow,
        'nestedInterface': value.nestedInterface,
        'nestedItem': value.nestedItem,
        'nestedMetadata': value.nestedMetadata,
        'nestedOccurrence': value.nestedOccurrence,
        'nestedPart': value.nestedPart,
        'nestedPort': value.nestedPort,
        'nestedReference': value.nestedReference,
        'nestedRendering': value.nestedRendering,
        'nestedRequirement': value.nestedRequirement,
        'nestedState': value.nestedState,
        'nestedTransition': value.nestedTransition,
        'nestedUsage': value.nestedUsage,
        'nestedUseCase': value.nestedUseCase,
        'nestedVerificationCase': value.nestedVerificationCase,
        'nestedView': value.nestedView,
        'nestedViewpoint': value.nestedViewpoint,
        'occurrenceDefinition': value.occurrenceDefinition,
        'output': value.output,
        'ownedAnnotation': value.ownedAnnotation,
        'ownedConjugator': value.ownedConjugator,
        'ownedDifferencing': value.ownedDifferencing,
        'ownedDisjoining': value.ownedDisjoining,
        'ownedElement': value.ownedElement,
        'ownedEndFeature': value.ownedEndFeature,
        'ownedFeature': value.ownedFeature,
        'ownedFeatureChaining': value.ownedFeatureChaining,
        'ownedFeatureInverting': value.ownedFeatureInverting,
        'ownedFeatureMembership': value.ownedFeatureMembership,
        'ownedImport': value.ownedImport,
        'ownedIntersecting': value.ownedIntersecting,
        'ownedMember': value.ownedMember,
        'ownedMembership': value.ownedMembership,
        'ownedRedefinition': value.ownedRedefinition,
        'ownedReferenceSubsetting': value.ownedReferenceSubsetting,
        'ownedRelationship': value.ownedRelationship,
        'ownedSpecialization': value.ownedSpecialization,
        'ownedSubsetting': value.ownedSubsetting,
        'ownedTypeFeaturing': value.ownedTypeFeaturing,
        'ownedTyping': value.ownedTyping,
        'ownedUnioning': value.ownedUnioning,
        'owner': value.owner,
        'owningDefinition': value.owningDefinition,
        'owningFeatureMembership': value.owningFeatureMembership,
        'owningMembership': value.owningMembership,
        'owningNamespace': value.owningNamespace,
        'owningRelationship': value.owningRelationship,
        'owningType': value.owningType,
        'owningUsage': value.owningUsage,
        'parameter': value.parameter,
        'portionKind': value.portionKind,
        'portioningFeature': value.portioningFeature,
        'predicate': value.predicate,
        'qualifiedName': value.qualifiedName,
        'reqId': value.reqId,
        'requiredConstraint': value.requiredConstraint,
        'requirementDefinition': value.requirementDefinition,
        'result': IdentifiedToJSON(value.result),
        'shortName': value.shortName,
        'stakeholderParameter': value.stakeholderParameter,
        'subjectParameter': IdentifiedToJSON(value.subjectParameter),
        'text': value.text,
        'textualRepresentation': value.textualRepresentation,
        'type': value.type,
        'unioningType': value.unioningType,
        'usage': value.usage,
        'variant': value.variant,
        'variantMembership': value.variantMembership,
        'viewpointDefinition': value.viewpointDefinition,
        'viewpointStakeholder': value.viewpointStakeholder,
    };
}

